shortener/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('url.urls', namespace="url")),
    
    
    path('api/', include('url.api.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

url/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.urlShortCreateView.as_view(), name="home"),
    path("all-urls/", views.AllUrl.as_view(), name="all_urls"),
    path("shortened-url-list/<slug>/", views.ShortenedUrlListView.as_view(), name="shortened_url_list"),
    path("delete-url/<pk>/", views.UrlDeleteView.as_view(), name="delete_url"),
    path("<slug>/", views.RedirectView.as_view(), name="redirect"),
    path("original-url/<pk>/", views.UrlDetailView.as_view(), name="original_url"),
]

url/urls.py
from django.urls import path
from . import views
app_name = "url"
urlpatterns = [
    path("short/", views.urlShort, name="short"),
    path("u/<str:slugs>/", views.urlRedirect, name="redirect"),
    path("", views.ShortenedUrlListView.as_view(), name="shortened_url_list"),
    path("original-url/<slug>/", views.UrlDetailView.as_view(), name="original_url"),
    path("delete-url/<slug>/", views.UrlDeleteView.as_view(), name="delete_url"),
]

url/models.py
from django.db import models

class UrlData(models.Model):
    url = models.CharField(max_length=800)
    slug = models.CharField(unique=True, max_length=15)
    domain = models.CharField(max_length=800, null=True)
    
    def __str__(self):
            return self.url

    def get_short_url(self):
        return f"{self.domain}{self.slug}"

url/forms.py
from django import forms
class Url(forms.Form):
    url = forms.CharField(label="URL")

url/api/views.py
from .serializers import UrlSerializer, ShortUrlListSerializer
from url.models import UrlData
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.generics import CreateAPIView,ListAPIView, DestroyAPIView, RetrieveAPIView
from rest_framework.status import HTTP_201_CREATED,HTTP_400_BAD_REQUEST
import random, string
from django.conf import settings

def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # if the randomly generated short_id is used then generate next
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        try:
            temp = UrlData.objects.get(slug=short_id)
        except:
            return short_id

class urlShortCreateView(APIView):
    def post(self, request, *args, **kwargs):
        serializer = UrlSerializer(data=request.data)

        slug = get_short_code()
        url = request.data.get('url', None)

        if url.startswith("https://www."):
            initial = "https://www."
            url = url.replace("https://www.", "")
            print(url)

        elif url.startswith("https://"):
            initial = "https://www."
            url = url.replace("https://", "")
            print(url)
        
        elif url.startswith("http://www."):
            initial = "https://www."
            url = url.replace("http://www.", "")
            print(url)

        elif url.startswith("http://"):
            initial = "https://www."
            url = url.replace("http://", "")
            print(url)

        elif url.startswith("www."):
            initial = "www."
            url = url.replace("www.", "")
            print(url)

        len = url.find("/")
        domain = url[:len+1]

        data = UrlData.objects.all()
        url = initial+url
        d= UrlData.objects.filter(url=url)
        if d.exists():
            return Response({"message": "this url is already shotrened"}, status=HTTP_400_BAD_REQUEST)
            
        new_url = UrlData(url=url, slug=slug,domain=domain)
        new_url.save()
        obj = UrlData.objects.all()
        serializer = UrlSerializer(obj, many=True)
        return Response({"data":serializer.data}, status=HTTP_201_CREATED)
   
class AllUrl(APIView):
    def get(self, request, *args, **kwargs):
        obj = UrlData.objects.all()
        application_list = []
        new=[]
        for m in obj:
            obj = {}
            obj['domain'] = m.domain
            obj['slug'] = m.slug
            application_list.append(obj)
            
            new.append(obj['domain']+obj['slug'])

        return Response({"data":new})
        
class ShortenedUrlListView(APIView):
    def get(self, request, slug, *args, **kwargs):
        obj = UrlData.objects.all()
        try:
            l = [x for x in obj if x.slug==slug]
            short_url = l[0].domain+l[0].slug
            return Response(short_url)
        except:
            return Response({"error": "url does not exists"})
        
class UrlDeleteView(DestroyAPIView):
    serializer_class = ShortUrlListSerializer
    queryset = UrlData.objects.all()
    
class UrlDetailView(RetrieveAPIView):
    serializer_class = ShortUrlListSerializer
    queryset = UrlData.objects.all()

class RedirectView(APIView):
    def get(self, request, slug, *args, **kwargs):
        obj = UrlData.objects.get(slug=slug)
        serializer = UrlSerializer(obj)
        return Response({"data":serializer.data})

url/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import DeleteView
from django.shortcuts import render,redirect
from .forms import Url
from .models import UrlData
import random, string
from django.urls import reverse_lazy
from django.contrib import messages


def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    while True:
        short_id = ''.join(random.choice(char) for _ in range(length))
        try:
            temp = UrlData.objects.get(slug=short_id)
        except:
            return short_id

def urlShort(request):
    if request.method == 'POST':
        form = Url(request.POST)
        if form.is_valid():
            slug = get_short_code()
            url = form.cleaned_data["url"]

            if url.startswith("https://www."):
                initial = "https://www."
                url = url.replace("https://www.", "")
                print(url)

            elif url.startswith("https://"):
                initial = "https://www."
                url = url.replace("https://", "")
                print(url)
            
            elif url.startswith("http://www."):
                initial = "https://www."
                url = url.replace("http://www.", "")
                print(url)

            elif url.startswith("http://"):
                initial = "https://www."
                url = url.replace("http://", "")
                print(url)

            elif url.startswith("www."):
                initial = "www."
                url = url.replace("www.", "")
                print(url)

            len = url.find("/")
            domain = url[:len+1]

            data = UrlData.objects.all()
            url = initial+url
            d= UrlData.objects.filter(url=url)
            if d.exists():
                messages.warning(request, "this url is already shotrened")
                return redirect(".")
            
            

            new_url = UrlData(url=url, slug=slug,domain=domain)
            new_url.save()
            messages.success(request, "url shortened successfully")
            return redirect('.')
    else:
        form = Url()
    data = UrlData.objects.all()
    context = {
        'form': form,
        'data': data
    }
    return render(request, 'index.html', context)


def urlRedirect(request, slugs):
    data = UrlData.objects.get(slug=slugs)
    return redirect(data.url)


class ShortenedUrlListView(ListView):
    model = UrlData
    template_name = "url/shortened_url_list.html"
    
class UrlDetailView(DetailView):
    model = UrlData
    template_name = "url/original_url.html"

class UrlDeleteView(DeleteView):
    model = UrlData
    template_name = "url/delete_confirm.html"
    success_url = reverse_lazy('url:shortened_url_list')

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    {% include 'navbar.html' %}
    <title>url shoretner</title>
  </head>
  <body>
    <div class="col-9 mx-auto mt-4">
    {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="col mx-auto mt-4">
    <form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-light btn-outline-info btn-block" type="submit" value="submit">
    </form>
<table class="table table-striped table-bordered  border-success">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Shortened Urls</th>
      <th scope="col">original Urls</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for d in data %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td><a href= "{% url 'url:redirect' d.slug %}"> {{d.get_short_url}} </a></td>
      <td> {{d.url|truncatechars:80}}</td>
      <td><a href= "{% url 'url:delete_url' d.slug %}" class="btn btn-danger">delete</a>
      </td>
    

    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Url Shortener  </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'url:short' %}">Short Url</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/url/delete_confirm.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
<h5>Are you sure, this can not be undone!!!</h5>
<input class="btn btn-light btn-outline-danger" type="submit" value="confirm">
</form>
{% endblock content %}

templates/url/original_url.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
  <div class="card-header">
    <strong>original Urls</strong> <a class=" btn btn-light text-info" href="{% url 'url:shortened_url_list' %}">go back to list</a>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><a href="{{object.url}}">{{object.url}}</a></li>
  </ul>
</div>
{% endblock content %}

templates/url/shortened_url_list.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-info border-success h4">Welcome to Url Shortener Service</div>
<p>Fetch origial url from shorttened url. for creating short url, and to navigate to the original URL by clicking on the shortened URL click <a href="{% url 'url:short' %}">here.</a></p>
<div style="overflow-x:auto">
<table class="table table-striped table-bordered  border-success">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Shortened Urls</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in object_list %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td><a href= "{% url 'url:original_url' obj.slug %}"> {{obj.get_short_url}} </a></td>
      <td><a href= "{% url 'url:delete_url' obj.slug %}" class="btn btn-danger"> delete </a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock content %}